name: CI/CD Workflow

on:
  push:
    branches:
      - dev

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 새로운 브랜치 생성
      - name: Create new branch
        run: |
          git checkout -b temp-branch-${{ github.run_id }}
          echo "New branch created: temp-branch-${{ github.run_id }}"

      # 3. 빌드 실행
      - name: Build project
        run: |
          echo "Running build steps..."
          # 실제 빌드 명령어로 대체하세요 (예: npm install && npm run build)
          npm install && npm run build

      # 4. dev 브랜치로 복귀
      - name: Checkout dev branch
        run: |
          git checkout dev
          echo "Checked out to dev branch"

      # 5. 새로 생성한 브랜치 삭제
      - name: Delete new branch
        run: |
          git branch -D temp-branch-${{ github.run_id }}
          echo "Deleted temp-branch-${{ github.run_id }}"
